services:
  ingestion:
    build: 
      context: ../ingestion  # Вказуємо шлях до папки з кодом Ingestion
      dockerfile: Dockerfile
    env_file:
      - ../.env              # Підтягуємо спільні конфіги з кореня
    depends_on:
      - kafka                # Чекаємо на запуск брокера
    restart: always          # Автоматично перезапускати, якщо впаде

  # api:
  #   build: 
  #     context: ../api        # Вказуємо шлях до папки з кодом API
  #     dockerfile: Dockerfile
  #   env_file:
  #     - ../.env              # Підтягуємо ті самі конфіги (для Cassandra/Redis)
  #   ports:
  #     - "8000:8000"          # Відкриваємо порт для доступу зовні
  #   depends_on:
  #     - cassandra            # Чекаємо на базу даних
  #     - redis                # Чекаємо на кеш
  #   restart: always