services:
  ingestion:
    build: 
      context: ../ingestion
      dockerfile: Dockerfile
    depends_on:
      kafka-setup:
        condition: service_completed_successfully
    restart: always

  api:
    build: 
      context: ../api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      redis:
        condition: service_started
      cassandra:
        condition: service_healthy
    restart: always