services:
  kafka:
    image: apache/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      # Постійний ID кластера, щоб дані не "відвалювались" після перезапуску
      KAFKA_KRAFT_CLUSTER_ID: 62fba63a-bf92-4f9c-8168-bfedbeba5dc9
    healthcheck:
      test: ["CMD-SHELL", "/opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --list"]
      interval: 5s
      timeout: 5s
      retries: 5
    env_file:
      - ../.env
    volumes:
      - kafka_data:/kafka

  kafka-setup:
    image: apache/kafka:latest
    depends_on:
      kafka:
        condition: service_healthy
    command: >
      bash -c "
        /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka:9092 --create --if-not-exists --topic raw-page-creates --partitions 3
        echo 'Topic raw-page-creates created successfully.'
      "

  # Додаю UI для зручності — ти зможеш зайти на http://localhost:8080 
  # і побачити свої топіки та повідомлення очима.
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8085:8085"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
    depends_on:
      - kafka

volumes:
  kafka_data:
    driver: local